### ISSUE TITLE
Dataset google drive link is unavailable

### ISSUE THREAD

**Issue by wsjxdy** [showlab/Efficient-CLS#3]
Hello, thank you for your great work! The Google Drive link to the dataset you provided seems to be unavailable. The link connects to this project, not the dataset.

**Comment by zhangjiewu** [comment]
The links are now updated.

**Comment by wsjxdy** [comment]
> The links are now updated.

Thank you for your prompt reply! However, I have downloaded the oka data file multiple times, but the connection fails every time when the download reaches 86% (including using the Internet Download Manager).
1. Could you please provide other cloud links (such as Baidu Cloud).
2. In addition, I would like to ask whether the necessary files such as "train_anno2/4/... .csv" required to run the code also included in the uploaded data?
Looking forward to your prompt reply! Thank you very much!
![jpg](https://github.com/showlab/Efficient-CLS/assets/54841820/6e712f41-c70a-4c57-9914-e85f34a036ba)
![jpg2](https://github.com/showlab/Efficient-CLS/assets/54841820/c9c302f7-5a49-48fd-a1aa-9b8f125a0b59)

**Comment by ldy674** [comment]
Hi author, I'm having the same problem downloading the dataset, can you provide a link to another download?

**Comment by zhangjiewu** [comment]
I have re-uploaded the datasets. Downloading works well on my end. Can you try the links below?

OAK: https://drive.google.com/file/d/1TewbRDPhutTDHT5vl_0hE30hotZqcffV/view?usp=sharing
EgoObjects: https://drive.google.com/file/d/10d0XSS5G_HW4P8ptVh7k-PT50Phmb3XN/view?usp=sharing 

I am also working on other cloud platforms.

**Comment by wsjxdy** [comment]
> I have re-uploaded the datasets. Downloading works well on my end. Can you try the links below?
> 
> OAK: https://drive.google.com/file/d/1TewbRDPhutTDHT5vl_0hE30hotZqcffV/view?usp=sharing EgoObjects: https://drive.google.com/file/d/10d0XSS5G_HW4P8ptVh7k-PT50Phmb3XN/view?usp=sharing
> 
> I am also working on other cloud platforms.

@zhangjiewu Thank you for your reply. It works~
I have successfully downloaded the OAK dataset. In order to help Chinese scholars download it easily, I uploaded the OAK dataset to Baidu Cloud and shared the link as follows:
Link：https://pan.baidu.com/s/18JWv1ouNKWDfOg2GTwBoeg?pwd=xyre 
Access code：xyre
